# Loggy AI services definition

service: analyze_logs
description: "Analyze logs with the Loggy AI integration."
fields:
  key:
    description: "API key to perform the analysis."
    required: true
    type: string
